print ("Introduction to Git, interesting")
print ("Hello, Hello, Hello")
print( "welcome new set of software engineers")
print('powell wrote this kids')
print('watermelon')
print("melvin is greeting")
print("bri happens to be cheesy")
print("michael lover of God")
print("chidera added new line")